version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - SERVER_PORT= 8181
      - SPRING_DATASOURCE_URL=jdbc:mysql://localhost:3306/mokriy_nos_app_db
    ports:
      - "8181:8181"
    depends_on:
      service-db:
        condition: service_healthy

  service-db:
    image: mysql:8.0.27
    environment:
      MYSQL_SERVER: mokriy_nos_app_db
      MYSQL_USER: root
      MYSQL_PASSWORD: 1234
    ports:
      - "3306:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10
    restart: unless-stopped